export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT';
export const GET_RESTAURANT = 'GET_RESTAURANT';

export const SHOW_CONTACT = 'SHOW_CONTACT';

export const GET_PRODUCTS = 'GET_PRODUCTS';

