export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const DESELECT_RESTAURANT = 'DESELECT_RESTAURANT';
export const GET_RESTAURANT = 'GET_RESTAURANT';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

